- name: create {{ user_name }} user
  user: name={{ user_name }} state=present shell=/bin/bash

- name: is there a ssh key for {{ user_name }} ?
  stat: path="ssh_keys/{{ user_name }}.pub"
  register: user_ssh_key
  delegate_to: localhost
  become: False

- name: install ssh key for {{ user_name }}
  authorized_key: user={{ user_name }} key="{{ lookup('file', 'ssh_keys/{{ user_name }}.pub') }}" state=present
  when: "{{ user_ssh_key.stat.exists }}"

- name: make {{ user_name }} sudoer
  user: name={{ user_name }} append=yes groups=sudo
  when: user_sudoer

- name: sudo group members don't need a password
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'

